// import { Images } from "../images/images";

// export const CoffeeData = [
//   {
//     id: 1,
//     category: "Americano",
//     name: "Americano",
//     description: "description about the coffee/bean",
//     image: Images.blackCoffee,
//     detailsImg: Images.blackCoffeeDetails,
//     prices: [
//       { size: "S", price: 2.99, quantity: 0 },
//       { size: "M", price: 3.99, quantity: 0 },
//       { size: "L", price: 5.99, quantity: 0 },
//     ],
//     ingredients: "Milk",
//     average_rating: 4.6,
//     favorite: false,
//   },
//   {
//     id: 2,
//     category: "Americano",
//     name: "Americano",
//     description: "description about the coffee/bean",
//     image: Images.blackCoffee,
//     detailsImg: Images.blackCoffeeDetails,
//     prices: [
//       { size: "S", price: 2.99, quantity: 0 },
//       { size: "M", price: 3.99, quantity: 0 },
//       { size: "L", price: 5.99, quantity: 0 },
//     ],
//     ingredients: "Milk",
//     average_rating: 4.6,
//     favorite: false,
//   },
//   {
//     id: 3,
//     category: "Americano",
//     name: "Americano",
//     description: "description about the coffee/bean",
//     image: Images.blackCoffee,
//     detailsImg: Images.blackCoffeeDetails,
//     prices: [
//       { size: "S", price: 2.99, quantity: 0 },
//       { size: "M", price: 3.99, quantity: 0 },
//       { size: "L", price: 5.99, quantity: 0 },
//     ],
//     ingredients: "Milk",
//     average_rating: 4.6,
//     favorite: false,
//   },
//   {
//     id: 4,
//     category: "black coffee",
//     name: "black coffee",
//     description: "description about the coffee/bean",
//     image: Images.blackCoffee,
//     detailsImg: Images.blackCoffeeDetails,
//     prices: [
//       { size: "S", price: 2.99, quantity: 0 },
//       { size: "M", price: 3.99, quantity: 0 },
//       { size: "L", price: 5.99, quantity: 0 },
//     ],
//     ingredients: "Milk",
//     average_rating: 4.6,
//     favorite: false,
//   },
//   {
//     id: 5,
//     category: "black coffee",
//     name: "black coffee",
//     description: "description about the coffee/bean",
//     image: Images.blackCoffee,
//     detailsImg: Images.blackCoffeeDetails,
//     prices: [
//       { size: "S", price: 2.99, quantity: 0 },
//       { size: "M", price: 3.99, quantity: 0 },
//       { size: "L", price: 5.99, quantity: 0 },
//     ],
//     ingredients: "Milk",
//     average_rating: 4.6,
//     favorite: false,
//   },
//   {
//     id: 6,
//     category: "black coffee",
//     name: "black coffee",
//     description: "description about the coffee/bean",
//     image: Images.blackCoffee,
//     detailsImg: Images.blackCoffeeDetails,
//     prices: [
//       { size: "S", price: 2.99, quantity: 0 },
//       { size: "M", price: 3.99, quantity: 0 },
//       { size: "L", price: 5.99, quantity: 0 },
//     ],
//     ingredients: "Milk",
//     average_rating: 4.6,
//     favorite: false,
//   },
//   {
//     id: 7,
//     category: "cappuccino",
//     name: "cappuccino",
//     description: "description about the coffee/bean",
//     image: Images.blackCoffee,
//     detailsImg: Images.blackCoffeeDetails,
//     prices: [
//       { size: "S", price: 2.99, quantity: 0 },
//       { size: "M", price: 3.99, quantity: 0 },
//       { size: "L", price: 5.99, quantity: 0 },
//     ],
//     ingredients: "Milk",
//     average_rating: 4.6,
//     favorite: false,
//   },
//   {
//     id: 8,
//     category: "cappuccino",
//     name: "cappuccino",
//     description: "description about the coffee/bean",
//     image: Images.blackCoffee,
//     detailsImg: Images.blackCoffeeDetails,
//     prices: [
//       { size: "S", price: 2.99, quantity: 0 },
//       { size: "M", price: 3.99, quantity: 0 },
//       { size: "L", price: 5.99, quantity: 0 },
//     ],
//     ingredients: "Milk",
//     average_rating: 4.6,
//     favorite: false,
//   },
//   {
//     id: 9,
//     category: "cappuccino",
//     name: "cappuccino",
//     description: "description about the coffee/bean",
//     image: Images.blackCoffee,
//     detailsImg: Images.blackCoffeeDetails,
//     prices: [
//       { size: "S", price: 2.99, quantity: 0 },
//       { size: "M", price: 3.99, quantity: 0 },
//       { size: "L", price: 5.99, quantity: 0 },
//     ],
//     ingredients: "Milk",
//     average_rating: 4.6,
//     favorite: false,
//   },
//   {
//     id: 10,
//     category: "espresso",
//     name: "espresso",
//     description: "description about the coffee/bean",
//     image: Images.blackCoffee,
//     detailsImg: Images.blackCoffeeDetails,
//     prices: [
//       { size: "S", price: 2.99, quantity: 0 },
//       { size: "M", price: 3.99, quantity: 0 },
//       { size: "L", price: 5.99, quantity: 0 },
//     ],
//     ingredients: "Milk",
//     average_rating: 4.6,
//     favorite: false,
//   },
//   {
//     id: 11,
//     category: "espresso",
//     name: "espresso",
//     description: "description about the coffee/bean",
//     image: Images.blackCoffee,
//     detailsImg: Images.blackCoffeeDetails,
//     prices: [
//       { size: "S", price: 2.99, quantity: 0 },
//       { size: "M", price: 3.99, quantity: 0 },
//       { size: "L", price: 5.99, quantity: 0 },
//     ],
//     ingredients: "Milk",
//     average_rating: 4.6,
//     favorite: false,
//   },
//   {
//     id: 12,
//     category: "espresso",
//     name: "espresso",
//     description: "description about the coffee/bean",
//     image: Images.blackCoffee,
//     detailsImg: Images.blackCoffeeDetails,
//     prices: [
//       { size: "S", price: 2.99, quantity: 0 },
//       { size: "M", price: 3.99, quantity: 0 },
//       { size: "L", price: 5.99, quantity: 0 },
//     ],
//     ingredients: "Milk",
//     average_rating: 4.6,
//     favorite: false,
//   },
//   {
//     id: 13,
//     category: "latte",
//     name: "latte",
//     description: "description about the coffee/bean",
//     image: Images.blackCoffee,
//     detailsImg: Images.blackCoffeeDetails,
//     prices: [
//       { size: "S", price: 2.99, quantity: 0 },
//       { size: "M", price: 3.99, quantity: 0 },
//       { size: "L", price: 5.99, quantity: 0 },
//     ],
//     ingredients: "Milk",
//     average_rating: 4.6,
//     favorite: false,
//   },
//   {
//     id: 14,
//     category: "latte",
//     name: "latte",
//     description: "description about the coffee/bean",
//     image: Images.blackCoffee,
//     detailsImg: Images.blackCoffeeDetails,
//     prices: [
//       { size: "S", price: 2.99, quantity: 0 },
//       { size: "M", price: 3.99, quantity: 0 },
//       { size: "L", price: 5.99, quantity: 0 },
//     ],
//     ingredients: "Milk",
//     average_rating: 4.6,
//     favorite: false,
//   },
//   {
//     id: 15,
//     category: "latte",
//     name: "latte",
//     description: "description about the coffee/bean",
//     image: Images.blackCoffee,
//     detailsImg: Images.blackCoffeeDetails,
//     prices: [
//       { size: "S", price: 2.99, quantity: 0 },
//       { size: "M", price: 3.99, quantity: 0 },
//       { size: "L", price: 5.99, quantity: 0 },
//     ],
//     ingredients: "Milk",
//     average_rating: 4.6,
//     favorite: false,
//   },
//   {
//     id: 16,
//     category: "macchiato",
//     name: "macchiato",
//     description: "description about the coffee/bean",
//     image: Images.blackCoffee,
//     detailsImg: Images.blackCoffeeDetails,
//     prices: [
//       { size: "S", price: 2.99, quantity: 0 },
//       { size: "M", price: 3.99, quantity: 0 },
//       { size: "L", price: 5.99, quantity: 0 },
//     ],
//     ingredients: "Milk",
//     average_rating: 4.6,
//     favorite: false,
//   },
//   {
//     id: 17,
//     category: "macchiato",
//     name: "macchiato",
//     description: "description about the coffee/bean",
//     image: Images.blackCoffee,
//     detailsImg: Images.blackCoffeeDetails,
//     prices: [
//       { size: "S", price: 2.99, quantity: 0 },
//       { size: "M", price: 3.99, quantity: 0 },
//       { size: "L", price: 5.99, quantity: 0 },
//     ],
//     ingredients: "Milk",
//     average_rating: 4.6,
//     favorite: false,
//   },
//   {
//     id: 18,
//     category: "macchiato",
//     name: "macchiato",
//     description: "description about the coffee/bean",
//     image: Images.blackCoffee,
//     detailsImg: Images.blackCoffeeDetails,
//     prices: [
//       { size: "S", price: 2.99, quantity: 0 },
//       { size: "M", price: 3.99, quantity: 0 },
//       { size: "L", price: 5.99, quantity: 0 },
//     ],
//     ingredients: "Milk",
//     average_rating: 4.6,
//     favorite: false,
//   },
// ];
