import { Images } from "../images/images";

export const CoffeeData = [
  {
    id: 1,
    category: "Americano",
    name: "Americano",
    description: "description about the coffee/bean",
    image: Images.blackCoffee,
    detailsImg: Images.blackCoffeeDetails,
    prices: [
      { size: "S", price: 2.99 },
      { size: "M", price: 3.99 },
      { size: "L", price: 5.99 },
    ],
    ingredients: "Milk",
    average_rating: 4.6,
    favorite: false,
    quantity: 0,
  },
  {
    id: 2,
    category: "Americano",
    name: "Americano",
    description: "description about the coffee/bean",
    image: Images.blackCoffee,
    detailsImg: Images.blackCoffeeDetails,
    prices: [
      { size: "S", price: 2.99 },
      { size: "M", price: 3.99 },
      { size: "L", price: 5.99 },
    ],
    ingredients: "Milk",
    average_rating: 4.6,
    favorite: false,
    quantity: 0,
  },
  {
    id: 3,
    category: "Americano",
    name: "Americano",
    description: "description about the coffee/bean",
    image: Images.blackCoffee,
    detailsImg: Images.blackCoffeeDetails,
    prices: [
      { size: "S", price: 2.99 },
      { size: "M", price: 3.99 },
      { size: "L", price: 5.99 },
    ],
    ingredients: "Milk",
    average_rating: 4.6,
    favorite: false,
    quantity: 0,
  },
  {
    id: 4,
    category: "black coffee",
    name: "black coffee",
    description: "description about the coffee/bean",
    image: Images.blackCoffee,
    detailsImg: Images.blackCoffeeDetails,
    prices: [
      { size: "S", price: 2.99 },
      { size: "M", price: 3.99 },
      { size: "L", price: 5.99 },
    ],
    ingredients: "Milk",
    average_rating: 4.6,
    favorite: false,
    quantity: 0,
  },
  {
    id: 5,
    category: "black coffee",
    name: "black coffee",
    description: "description about the coffee/bean",
    image: Images.blackCoffee,
    detailsImg: Images.blackCoffeeDetails,
    prices: [
      { size: "S", price: 2.99 },
      { size: "M", price: 3.99 },
      { size: "L", price: 5.99 },
    ],
    ingredients: "Milk",
    average_rating: 4.6,
    favorite: false,
    quantity: 0,
  },
  {
    id: 6,
    category: "black coffee",
    name: "black coffee",
    description: "description about the coffee/bean",
    image: Images.blackCoffee,
    detailsImg: Images.blackCoffeeDetails,
    prices: [
      { size: "S", price: 2.99 },
      { size: "M", price: 3.99 },
      { size: "L", price: 5.99 },
    ],
    ingredients: "Milk",
    average_rating: 4.6,
    favorite: false,
    quantity: 0,
  },
  {
    id: 7,
    category: "cappuccino",
    name: "cappuccino",
    description: "description about the coffee/bean",
    image: Images.blackCoffee,
    detailsImg: Images.blackCoffeeDetails,
    prices: [
      { size: "S", price: 2.99 },
      { size: "M", price: 3.99 },
      { size: "L", price: 5.99 },
    ],
    ingredients: "Milk",
    average_rating: 4.6,
    favorite: false,
    quantity: 0,
  },
  {
    id: 8,
    category: "cappuccino",
    name: "cappuccino",
    description: "description about the coffee/bean",
    image: Images.blackCoffee,
    detailsImg: Images.blackCoffeeDetails,
    prices: [
      { size: "S", price: 2.99 },
      { size: "M", price: 3.99 },
      { size: "L", price: 5.99 },
    ],
    ingredients: "Milk",
    average_rating: 4.6,
    favorite: false,
    quantity: 0,
  },
  {
    id: 9,
    category: "cappuccino",
    name: "cappuccino",
    description: "description about the coffee/bean",
    image: Images.blackCoffee,
    detailsImg: Images.blackCoffeeDetails,
    prices: [
      { size: "S", price: 2.99 },
      { size: "M", price: 3.99 },
      { size: "L", price: 5.99 },
    ],
    ingredients: "Milk",
    average_rating: 4.6,
    favorite: false,
    quantity: 0,
  },
  {
    id: 10,
    category: "espresso",
    name: "espresso",
    description: "description about the coffee/bean",
    image: Images.blackCoffee,
    detailsImg: Images.blackCoffeeDetails,
    prices: [
      { size: "S", price: 2.99 },
      { size: "M", price: 3.99 },
      { size: "L", price: 5.99 },
    ],
    ingredients: "Milk",
    average_rating: 4.6,
    favorite: false,
    quantity: 0,
  },
  {
    id: 11,
    category: "espresso",
    name: "espresso",
    description: "description about the coffee/bean",
    image: Images.blackCoffee,
    detailsImg: Images.blackCoffeeDetails,
    prices: [
      { size: "S", price: 2.99 },
      { size: "M", price: 3.99 },
      { size: "L", price: 5.99 },
    ],
    ingredients: "Milk",
    average_rating: 4.6,
    favorite: false,
    quantity: 0,
  },
  {
    id: 12,
    category: "espresso",
    name: "espresso",
    description: "description about the coffee/bean",
    image: Images.blackCoffee,
    detailsImg: Images.blackCoffeeDetails,
    prices: [
      { size: "S", price: 2.99 },
      { size: "M", price: 3.99 },
      { size: "L", price: 5.99 },
    ],
    ingredients: "Milk",
    average_rating: 4.6,
    favorite: false,
    quantity: 0,
  },
  {
    id: 13,
    category: "latte",
    name: "latte",
    description: "description about the coffee/bean",
    image: Images.blackCoffee,
    detailsImg: Images.blackCoffeeDetails,
    prices: [
      { size: "S", price: 2.99 },
      { size: "M", price: 3.99 },
      { size: "L", price: 5.99 },
    ],
    ingredients: "Milk",
    average_rating: 4.6,
    favorite: false,
    quantity: 0,
  },
  {
    id: 14,
    category: "latte",
    name: "latte",
    description: "description about the coffee/bean",
    image: Images.blackCoffee,
    detailsImg: Images.blackCoffeeDetails,
    prices: [
      { size: "S", price: 2.99 },
      { size: "M", price: 3.99 },
      { size: "L", price: 5.99 },
    ],
    ingredients: "Milk",
    average_rating: 4.6,
    favorite: false,
    quantity: 0,
  },
  {
    id: 15,
    category: "latte",
    name: "latte",
    description: "description about the coffee/bean",
    image: Images.blackCoffee,
    detailsImg: Images.blackCoffeeDetails,
    prices: [
      { size: "S", price: 2.99 },
      { size: "M", price: 3.99 },
      { size: "L", price: 5.99 },
    ],
    ingredients: "Milk",
    average_rating: 4.6,
    favorite: false,
    quantity: 0,
  },
  {
    id: 16,
    category: "macchiato",
    name: "macchiato",
    description: "description about the coffee/bean",
    image: Images.blackCoffee,
    detailsImg: Images.blackCoffeeDetails,
    prices: [
      { size: "S", price: 2.99 },
      { size: "M", price: 3.99 },
      { size: "L", price: 5.99 },
    ],
    ingredients: "Milk",
    average_rating: 4.6,
    favorite: false,
    quantity: 0,
  },
  {
    id: 17,
    category: "macchiato",
    name: "macchiato",
    description: "description about the coffee/bean",
    image: Images.blackCoffee,
    detailsImg: Images.blackCoffeeDetails,
    prices: [
      { size: "S", price: 2.99 },
      { size: "M", price: 3.99 },
      { size: "L", price: 5.99 },
    ],
    ingredients: "Milk",
    average_rating: 4.6,
    favorite: false,
    quantity: 0,
  },
  {
    id: 18,
    category: "macchiato",
    name: "macchiato",
    description: "description about the coffee/bean",
    image: Images.blackCoffee,
    detailsImg: Images.blackCoffeeDetails,
    prices: [
      { size: "S", price: 2.99 },
      { size: "M", price: 3.99 },
      { size: "L", price: 5.99 },
    ],
    ingredients: "Milk",
    average_rating: 4.6,
    favorite: false,
    quantity: 0,
  },
];
